aws:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  instance_type: "t2.micro"
  security_group: "sg-your-security-group"
  ami_id: "ami-your-ubuntu-ami"

controller:
  port: 8080

bittorrent:
  github_repo: "https://github.com/fabioibanez/Rogue-Packet.git"
  torrent_url: "https://raw.githubusercontent.com/yourusername/bittorrent-project/main/test.torrent"

regions:
  - name: "us-east-1"
    seeders: 1
    leechers: 2

timeout_minutes: 30