aws:
  instance_type: t2.micro
  security_group: default
bittorrent:
  github_repo: https://github.com/fabioibanez/Rogue-Packet.git
  seed_fileurl: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex/distribed-reverted/seeder_sources/torrent_10.dat
  torrent_url: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex/distribed-reverted/torrents/torrent_10.dat.torrent
controller:
  port: 8080
regions:
- leechers: 4
  name: us-west-1
  seeders: 1
- leechers: 4
  name: us-west-2
  seeders: 1
timeout_minutes: 30
