aws:
  instance_type: t2.micro
  security_group: default
bittorrent:
  baseline_branch: vplex-final
  github_repo: https://github.com/fabioibanez/Rogue-Packet.git
  proportion_propshare: 0.5
  propshare_branch: master
  seed_fileurl: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex-final/seeder_sources/torrent_1.dat
  torrent_url: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex-final/torrents/torrent_1.dat.torrent
controller:
  port: 8080
regions:
- leechers: 12
  name: us-west-1
  seeders: 3
timeout_minutes: 30
