aws:
  instance_type: t2.micro
  security_group: default
bittorrent:
  github_repo: https://github.com/fabioibanez/Rogue-Packet.git
  seed_fileurl: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex/vplex-final/seeder_sources/torrent_2.dat
  torrent_url: https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/vplex/vplex-final/torrents/torrent_2.dat.torrent
  propshare_branch: master
  baseline_branch: vplex-final
  proportion_propshare: 0.5  # 60% of leechers use proportional-share, 40% use baseline-logging
controller:
  port: 8080
regions:

- leechers: 2
  name: us-west-1
  seeders: 1

# - leechers: 2
#   name: us-west-2
#   seeders: 1

timeout_minutes: 30