aws:
  instance_type: "t2.micro"
  security_group: "default"

controller:
  port: 8080

bittorrent:
  github_repo: "https://github.com/fabioibanez/Rogue-Packet.git"
  torrent_url: "https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/feat/distribed/torrents/pitch.pptx.torrent"
  seed_fileurl: "https://raw.githubusercontent.com/fabioibanez/Rogue-Packet/feat/distribed/seeder_sources/2025Spring-MM-Pitch.pptx"

regions:
  - name: "us-east-1"
    seeders: 2
    leechers: 5
  - name: "eu-west-1"
    seeders: 1
    leechers: 3
  - name: "ap-southeast-1"
    seeders: 1
    leechers: 2

timeout_minutes: 30